const ShopActionTypes = {
  FECTH_COLLECTIONS_START: "FECTH_COLLECTIONS_START",
  FECTH_COLLECTIONS_SUCCESS: "FECTH_COLLECTIONS_SUCCESS",
  FECTH_COLLECTIONS_FAILURE: "FECTH_COLLECTIONS_FAILURE",
};

export default ShopActionTypes;
